import {BaseEntity, Column, Entity, ManyToOne, PrimaryGeneratedColumn} from "typeorm";
import {CATEGORY, STATUS} from "./task.constants";
import {UserEntity} from "../auth/user.entity";


@Entity('Task')
export class TaskEntity extends BaseEntity {

    @PrimaryGeneratedColumn()
    id: number;

    @Column()
    title: string;

    @Column()
    status: STATUS ;

    @Column()
    timestamp : string;

    @Column()
    category : CATEGORY;

    //taskEntity has relationship with user entity, where in the entity, we can find tasks, {eager:false} when we fetch tasks, we might not need the user obj available immediately
    @ManyToOne(type => UserEntity, user=>user.tasks, {eager:false})
    user: UserEntity;

    //This column is autogenerated by ORM based on the relationship, but for queries we need define here
    @Column()
    userId: number
}
